version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb1
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express1
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongodb

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant1
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  backend:
    image: nnikolovskii/code_explore_backend
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb
      - qdrant
    ports:
      - "5000:5000"



volumes:
  mongo_data:
  qdrant_data: